# version: "3.9"

# services:
# laravelapp:
#     container_name: laravelapp
#     image: glasena/laravelapp:1.0.0
#     build: .
#     ports:
#         - "8000:8000"
#     env_file:
#         - .env
#     depends_on:
#         - db
services:
    db:
        container_name: postgres
        image: postgres:15
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=teste
            - POSTGRES_DB=postgres
        ports:
            - "5433:5432"
